export type Film = {
  id: string;
  year: string;
  title: string;
  universe: "Raimi" | "Webb" | "MCU" | "Spider-Verse";
  spider: string;
  foe: string;
  note: string;
  hue: string;
  upcoming?: boolean;
};

/* Chronological by release. Notes are Peter's voice; no plot is invented. */
export const films: Film[] = [
  {
    id: "01",
    year: "2002",
    title: "Spider-Man",
    universe: "Raimi",
    spider: "Tobey Maguire",
    foe: "Green Goblin",
    note: "Where it started. Directed by Sam Raimi. First swing, first mistake, first promise.",
    hue: "#e62429",
  },
  {
    id: "02",
    year: "2004",
    title: "Spider-Man 2",
    universe: "Raimi",
    spider: "Tobey Maguire",
    foe: "Doctor Octopus",
    note: "I tried to quit. The city had other plans. Four arms, one very bad day.",
    hue: "#e8a21a",
  },
  {
    id: "03",
    year: "2007",
    title: "Spider-Man 3",
    universe: "Raimi",
    spider: "Tobey Maguire",
    foe: "Sandman · Venom · New Goblin",
    note: "Three enemies, one dark suit, and a lot of me being my own worst problem.",
    hue: "#7a7f94",
  },
  {
    id: "04",
    year: "2012",
    title: "The Amazing Spider-Man",
    universe: "Webb",
    spider: "Andrew Garfield",
    foe: "The Lizard",
    note: "A different Peter, a different lab. Directed by Marc Webb. Science and a skateboard.",
    hue: "#2f6fe0",
  },
  {
    id: "05",
    year: "2014",
    title: "The Amazing Spider-Man 2",
    universe: "Webb",
    spider: "Andrew Garfield",
    foe: "Electro · Rhino",
    note: "The city lit up and so did he. Some lessons cost more than others.",
    hue: "#29b6e6",
  },
  {
    id: "06",
    year: "2016",
    title: "Captain America: Civil War",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "Team Iron Man vs Team Cap",
    note: "My first Avengers-sized day. Got a new suit. Got a taste of the big leagues.",
    hue: "#e62429",
  },
  {
    id: "07",
    year: "2017",
    title: "Spider-Man: Homecoming",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "The Vulture",
    note: "Back to the neighborhood. Directed by Jon Watts. School, homework, and a flying thief.",
    hue: "#e62429",
  },
  {
    id: "08",
    year: "2018",
    title: "Avengers: Infinity War",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "Thanos",
    note: "I don't feel so good. Neither did anyone in the theater.",
    hue: "#8a46d6",
  },
  {
    id: "09",
    year: "2018",
    title: "Spider-Man: Into the Spider-Verse",
    universe: "Spider-Verse",
    spider: "Shameik Moore as Miles Morales",
    foe: "Kingpin",
    note: "Anyone can wear the mask. Won the Oscar for Best Animated Feature.",
    hue: "#ff2bd6",
  },
  {
    id: "10",
    year: "2019",
    title: "Avengers: Endgame",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "Thanos",
    note: "Finished what we started. Everyone showed up.",
    hue: "#e8a21a",
  },
  {
    id: "11",
    year: "2019",
    title: "Spider-Man: Far From Home",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "Mysterio",
    note: "A school trip through Europe. My spider-sense had notes about the illusions.",
    hue: "#29b6e6",
  },
  {
    id: "12",
    year: "2021",
    title: "Spider-Man: No Way Home",
    universe: "MCU",
    spider: "Holland · Maguire · Garfield",
    foe: "Goblin · Octopus · Sandman · Lizard · Electro",
    note: "Three Peters, one rooftop. The biggest group project of my life.",
    hue: "#e62429",
  },
  {
    id: "13",
    year: "2023",
    title: "Spider-Man: Across the Spider-Verse",
    universe: "Spider-Verse",
    spider: "Shameik Moore as Miles Morales",
    foe: "The Spot",
    note: "The multiverse got bigger. So did the cast. So did the stakes.",
    hue: "#29e6ff",
  },
  {
    id: "14",
    year: "2026",
    title: "Spider-Man: Brand New Day",
    universe: "MCU",
    spider: "Tom Holland",
    foe: "Classified",
    note: "Newest entry on file. Check the theater listings for the details.",
    hue: "#e62429",
  },
  {
    id: "15",
    year: "2027",
    title: "Spider-Man: Beyond the Spider-Verse",
    universe: "Spider-Verse",
    spider: "Shameik Moore as Miles Morales",
    foe: "Classified",
    note: "Announced and in production. Not out yet — I'll be the one in line.",
    hue: "#ff2bd6",
    upcoming: true,
  },
];
